# Generated by Django 5.2.2 on 2025-06-05 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('Email', 'Email'), ('Telefono', 'Telefono'), ('Documento', 'Documento'), ('Call', 'Call'), ('Task', 'Task'), ('Decisione', 'Decisione')], max_length=50)),
                ('priorita', models.CharField(choices=[('urgent-important', 'Urgente e Importante'), ('important-not-urgent', 'Importante Non Urgente'), ('urgent-not-important', 'Urgente Non Importante'), ('not-urgent-not-important', 'Non Urgente Non Importante')], max_length=50)),
                ('completata', models.BooleanField(default=False)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('assegnato_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_assegnate', to=settings.AUTH_USER_MODEL)),
                ('creatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
