# Generated by Django 5.2.2 on 2025-06-09 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbk_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
