# Generated by Django 5.2.2 on 2025-06-09 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sbk_app', '0002_delete_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('Email', 'Email'), ('Telefono', 'Telefono'), ('Documento', 'Documento'), ('Call', 'Call'), ('Task', 'Task'), ('Decisione', 'Decisione')], max_length=20)),
                ('priorita', models.CharField(choices=[('UI', 'Urgente e Importante'), ('IN', 'Importante Non Urgente'), ('UN', 'Urgente Non Importante'), ('NN', 'Non Urgente Non Importante')], max_length=2)),
                ('completata', models.BooleanField(default=False)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('creatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
