# Generated by Django 5.2.2 on 2025-06-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbk_app', '0004_task_modificato_da_alter_task_descrizione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='modificato_da',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
