# Generated by Django 5.2.2 on 2025-06-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbk_app', '0008_task_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='data_completamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
