# Generated by Django 5.2.2 on 2025-06-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbk_app', '0009_task_data_completamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='data_archiviazione',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
