# Generated by Django 5.2.2 on 2025-06-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbk_app', '0010_task_data_archiviazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='archiviata',
            field=models.BooleanField(default=False),
        ),
    ]
