# Generated by Django 5.2.2 on 2025-06-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbk_app', '0011_task_archiviata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='data_archiviazione',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='data_completamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='data_creazione',
            field=models.DateField(auto_now_add=True),
        ),
    ]
