# Generated by Django 5.2.2 on 2025-06-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbk_app', '0012_alter_task_data_archiviazione_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='data_creazione',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
