# Generated by Django 5.2.2 on 2025-06-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbk_app', '0013_alter_task_data_creazione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='data_creazione',
            field=models.DateField(blank=True, null=True),
        ),
    ]
